[package]
name = "aoc2022"
version = "0.0.1"
edition = "2021"

[lib]

[[bin]]
name = "day1"

[[bin]]
name = "day2"

[dependencies]
anyhow = "1.0.66"
futures = "0.3.25"
rayon = "1.6.0"
structopt = "0.3.26"
tokio = { version = "1.22.0", features = [ "full" ] }
